version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000" 
      - "5001:5001"  
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db  

  frontend:
    build:
      context: ./frontend  
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: CMD mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: